# Generated by Django 3.2.9 on 2021-12-06 14:08

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
        migrations.AddField(
            model_name='certificate',
            name='landscape',
            field=models.BooleanField(default=False, verbose_name=django.forms.widgets.CheckboxInput),
        ),
    ]
